### ISSUE TITLE
Silence PHP Warning: unlink() in GC

### ISSUE THREAD

**Issue by fedys** [zendframework/zend-captcha#13]
Sometimes I get: _PHP Warning: unlink()_ due to concurrent requests on server. Thus `unlink($file->getPathname());` in method _\Zend\Captcha\Image::gc()_ should be silenced with: `@unlink($file->getPathname());`.

**Comment by samsonasik** [comment]
@fedys I've created PR #23 for it.

**Comment by fedys** [comment]
@samsonasik Thanks ;)
