### ISSUE TITLE
composer require zendframework/zend-captcha can't install php 7.1.16

### ISSUE THREAD

**Issue by MaxsHub** [zendframework/zend-captcha#41]
composer require zendframework/zend-captcha

Using version ^2.8 for zendframework/zend-captcha
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package zendframework/zend-form (locked at 2.10.2, required as ^2.12) is satisfiable by zendframework/zend-form[2.10.2] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Conclusion: don't install zendframework/zend-form 2.12.0
    - Conclusion: don't install zendframework/zend-form 2.13.x-dev
    - Conclusion: remove zendframework/zend-inputfilter 2.7.6
    - Installation request for zendframework/zend-form ^2.12 -> satisfiable by zendframework/zend-form[2.12.0, 2.13.x-dev, 2.12.x-dev].
    - Conclusion: don't install zendframework/zend-inputfilter 2.7.6
    - zendframework/zend-form 2.12.x-dev requires zendframework/zend-inputfilter ^2.8 -> satisfiable by zendframework/zend-inputfilter[2.8.0, 2.8.1, 2.8.2, 2.9.x-dev, 2.8.x-dev].
    - Can only install one of: zendframework/zend-inputfilter[2.8.0, 2.7.6].
    - Can only install one of: zendframework/zend-inputfilter[2.8.1, 2.7.6].
    - Can only install one of: zendframework/zend-inputfilter[2.8.2, 2.7.6].
    - Can only install one of: zendframework/zend-inputfilter[2.9.x-dev, 2.7.6].
    - Can only install one of: zendframework/zend-inputfilter[2.8.x-dev, 2.7.6].
    - Installation request for zendframework/zend-inputfilter (locked at 2.7.6) -> satisfiable by zendframework/zend-inputfilter[2.7.6].

Installation failed, reverting ./composer.json to its original content.

help me install packge

**Comment by Ocramius** [comment]
Read the exact message: some of your dependencies are locked, so you need to relax them before you upgrade any component.

**Comment by MaxsHub** [comment]
Thank my your forword
