### ISSUE TITLE
Unable to overwrite default options.

### ISSUE THREAD

**Issue by waltertamboer** [zendframework/zend-captcha#5]
There is an isset check around the setting of options. This fails when options have a default value that validates to false like `null`.

The line I'm talking about [can be found here](https://github.com/zendframework/zend-captcha/blob/master/src/ReCaptcha.php#L178).

See also: https://github.com/Lansoweb/LosReCaptcha/issues/3

**Comment by samsonasik** [comment]
should already fixed by #6 , close-able.
